import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The two brand marks are GENERATED (`npm run brand:build`), and the thing
 * generation buys is the colour mapping: the artwork ships three literal
 * colours — one of them the named colour `black`, not a hex triplet — and the
 * components must ship none of them.
 *
 * Both failures this catches are silent. Paste a fresh export's paths in by
 * hand and the mark renders perfectly — in one theme, painted black on a
 * ground that `.dark` will one day make black too. And svgo's `preset-default`
 * REMOVES `viewBox` on its own whenever width/height are present, which is not
 * a degradation but a deletion: the components size themselves from
 * `className` alone, so a viewBox-less mark renders at its intrinsic size or
 * not at all. `scripts/build-brand.ts`'s `removeViewBox: false` override
 * guards against exactly that.
 */
const MARKS = ["components/brand/ariko-icon.tsx", "components/brand/ariko-logo.tsx"];

/** Every fill a generated mark may carry — anything else is a leaked literal. */
const ALLOWED_FILL = /^(none|currentColor|var\(--ariko-leaf-(dark|light)\))$/;

for (const path of MARKS) {
  const source = readFileSync(join(process.cwd(), path), "utf8");

  test(`${path} paints from tokens, not literals`, () => {
    for (const [, value] of source.matchAll(/fill="([^"]+)"/g)) {
      assert.match(value, ALLOWED_FILL, `${path}: unexpected fill "${value}" — run \`npm run brand:build\``);
    }
    assert.ok(
      source.includes('fill="currentColor"'),
      `${path} must paint its letterforms with currentColor`,
    );
    assert.ok(
      source.includes("var(--ariko-leaf-dark)") && source.includes("var(--ariko-leaf-light)"),
      `${path} must paint its leaves from --ariko-leaf-* (app/globals.css)`,
    );
  });

  test(`${path} keeps its viewBox`, () => {
    assert.match(
      source,
      /viewBox="0 0 \d+ \d+"/,
      `${path} lost its viewBox — svgo's preset-default removes it unless overridden`,
    );
  });

  test(`${path} says it is generated`, () => {
    assert.ok(
      source.includes("GENERATED by `npm run brand:build`"),
      `${path} must carry the generated banner, so nobody edits it by hand`,
    );
  });
}

test("app/globals.css declares the leaf tokens the marks reference", () => {
  const css = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");

  assert.match(
    css,
    /--ariko-leaf-dark:\s*[^;]+;/,
    "app/globals.css must declare --ariko-leaf-dark — a rename here leaves the marks' leaves painted `fill=\"none\"` with the token pin still green",
  );
  assert.match(
    css,
    /--ariko-leaf-light:\s*[^;]+;/,
    "app/globals.css must declare --ariko-leaf-light — a rename here leaves the marks' leaves painted `fill=\"none\"` with the token pin still green",
  );
});
