import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The two brand marks are GENERATED (`npm run brand:build`), and the thing
 * generation buys is the colour mapping: the artwork ships three literal
 * colours and the components must ship none of them.
 *
 * Both failures this catches are silent. Paste a fresh export's paths in by
 * hand and the mark renders perfectly — in one theme, painted black on a
 * ground that `.dark` will one day make black too. And svgo's `preset-default`
 * REMOVES `viewBox` whenever width/height are present, which is not a
 * degradation but a deletion: the components size themselves from `className`
 * alone, so a viewBox-less mark renders at its intrinsic size or not at all.
 * That one bit someone during the build of this very slice.
 */
const MARKS = ["components/brand/ariko-icon.tsx", "components/brand/ariko-logo.tsx"];

for (const path of MARKS) {
  test(`${path} paints from tokens, not literals`, () => {
    const source = readFileSync(join(process.cwd(), path), "utf8");

    assert.ok(
      !/fill="#[0-9a-fA-F]{3,8}"/.test(source),
      `${path} must carry no literal hex fill — run \`npm run brand:build\``,
    );
    assert.ok(
      source.includes('fill="currentColor"'),
      `${path} must paint its letterforms with currentColor`,
    );
    assert.ok(
      source.includes("var(--ariko-leaf-dark)") && source.includes("var(--ariko-leaf-light)"),
      `${path} must paint its leaves from --ariko-leaf-* (app/globals.css)`,
    );
  });

  test(`${path} keeps its viewBox`, () => {
    const source = readFileSync(join(process.cwd(), path), "utf8");

    assert.match(
      source,
      /viewBox="0 0 \d+ \d+"/,
      `${path} lost its viewBox — svgo's preset-default removes it unless overridden`,
    );
  });

  test(`${path} says it is generated`, () => {
    const source = readFileSync(join(process.cwd(), path), "utf8");

    assert.ok(
      source.includes("GENERATED by `npm run brand:build`"),
      `${path} must carry the generated banner, so nobody edits it by hand`,
    );
  });
}
