import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { optimize } from "svgo";
import sharp from "sharp";

/**
 * The only writer of derived brand artifacts. Two sources in
 * (`assets/brand/*.svg`); this pass derives every file below in memory and
 * only then writes them, in one batch, sized by the `files` array in `main`.
 *
 * It exists because the alternative is that the next person to change the logo
 * re-derives the colour mapping, the precision setting, the maskable safe zone
 * and the Apple background from scratch — or, far likelier, does not, and ships
 * a manifest icon that disagrees with the favicon.
 *
 * Run it by hand (`npm run brand:build`), not at build time: the brand changes
 * at the pace of a rebrand, not a deploy, and every output is committed.
 */

const ROOT = process.cwd();

/** The three literal colours the artwork ships, as svgo normalises them (`black` → `#000`), and the tokens they become. */
const INK = "#000";
const LEAF_DARK = "#006400";
const LEAF_LIGHT = "#90ee90";

/**
 * `removeViewBox: false` is defence in depth, not a preference. preset-default
 * ALONE deletes viewBox when width/height are present, leaving a mark that
 * sizes itself from a `className` it no longer has. `removeDimensions`
 * happens to rebuild the viewBox from width/height afterwards, so today the
 * override changes nothing — which is exactly why it stays: it makes the
 * viewBox independent of that coincidence, and of plugin order.
 */
function tidy(source: string): string {
  const { data } = optimize(source, {
    floatPrecision: 1,
    plugins: [
      { name: "preset-default", params: { overrides: { removeViewBox: false } } },
      "removeDimensions",
    ],
  });
  return data;
}

function viewBoxOf(svg: string): string {
  const found = svg.match(/viewBox="([^"]+)"/);
  if (!found) throw new Error("svgo stripped the viewBox — check the plugin overrides");
  return found[1];
}

/** svgo emits only these four on this artwork; anything else is a surprise worth failing on. */
const JSX_ATTR: Record<string, string> = {
  d: "d",
  fill: "fill",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
};

function toToken(value: string): string {
  const v = value.toLowerCase();
  if (v === INK) return "currentColor";
  if (v === LEAF_DARK) return "var(--ariko-leaf-dark)";
  if (v === LEAF_LIGHT) return "var(--ariko-leaf-light)";
  throw new Error(`unexpected colour ${value} — the artwork's palette changed`);
}

function pathsToJsx(svg: string): string {
  const tags = svg.match(/<path\b[^>]*\/?>/g) ?? [];
  if (tags.length === 0) throw new Error("no <path> elements — did the export change shape?");

  /**
   * Everything in the tidied SVG other than the root tag and the <path>s we
   * just matched. A `<circle>`, a `<rect>`, a stray `<g>` — anything else
   * survives svgo's preset and would otherwise be dropped here silently,
   * exit 0, with the artwork missing a piece in all seven derived files.
   */
  const leftover = svg
    .replace(/<\/?svg\b[^>]*>/g, "")
    .replace(/<path\b[^>]*\/?>/g, "")
    .trim();
  if (leftover) {
    throw new Error(`unhandled SVG content: ${leftover.slice(0, 80)}`);
  }

  return tags
    .map((tag) => {
      const attrs = [...tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)].map(([, name, value]) => {
        const jsxName = JSX_ATTR[name];
        if (!jsxName) throw new Error(`unmapped SVG attribute \`${name}\``);
        return [jsxName, name === "fill" ? toToken(value) : value] as const;
      });
      const rendered = attrs.map(([n, v]) => `\n        ${n}="${v}"`).join("");
      return `      <path${rendered}\n      />`;
    })
    .join("\n");
}

function component(name: string, svg: string): string {
  return `import type { SVGProps } from "react";

// GENERATED by \`npm run brand:build\` from assets/brand/*.svg. Do not edit.

/**
 * The letterforms are painted with \`currentColor\`, so they follow the text
 * colour of whatever they sit in (\`text-foreground\`, \`text-primary\`, …). The
 * two leaf greens come from \`--ariko-leaf-dark\` / \`--ariko-leaf-light\`, which
 * \`app/globals.css\` re-declares under \`.dark\`.
 */
export function ${name}({ title, ...props }: SVGProps<SVGSVGElement> & { title?: string }) {
  return (
    <svg
      viewBox="${viewBoxOf(svg)}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      role={title ? "img" : "presentation"}
      aria-hidden={title ? undefined : true}
    >
      {title ? <title>{title}</title> : null}
${pathsToJsx(svg)}
    </svg>
  );
}
`;
}

/**
 * The favicon is the one derivative that CANNOT use currentColor — it renders
 * outside the document. An embedded <style> gives it the same two-tone
 * behaviour the two `media`-switched PNGs had, in one file instead of 386 kB.
 *
 * `#111` / `#fafafa` are hand-conversions of `--foreground` under `:root` and
 * `.dark` (`app/globals.css:34` and `:73` — `oklch(0.145 0 0)` /
 * `oklch(0.985 0 0)`). A future edit to either token desyncs the tab icon
 * with nothing to notice, which is what the two throws below guard against:
 * `.replaceAll`/`.replace` return their input unchanged on a non-match, so a
 * shape change upstream (the exported root tag loses its `fill="#000"`, say)
 * would otherwise ship an untinted, invisible favicon on a green build.
 */
function buildFavicon(icon: string): string {
  const inked = icon.replaceAll(`fill="${INK}"`, 'class="ink"');
  if (inked === icon) {
    throw new Error(`no fill="${INK}" to theme — the favicon would ship untinted`);
  }

  const favicon = inked.replace(
    /(<svg[^>]*>)/,
    "$1<style>.ink{fill:#111}@media(prefers-color-scheme:dark){.ink{fill:#fafafa}}</style>",
  );
  if (favicon === inked) {
    throw new Error("no <svg> open tag found — the favicon lost its <style>");
  }

  return favicon;
}

type Rgba = { r: number; g: number; b: number; alpha: number };

const CLEAR: Rgba = { r: 0, g: 0, b: 0, alpha: 0 };
const WHITE: Rgba = { r: 255, g: 255, b: 255, alpha: 1 };

/**
 * sharp rasterises SVG at 72dpi by default. `removeDimensions` leaves the
 * source with a viewBox and no width/height, so at the default it comes out
 * at exactly its viewBox — 320×320, BELOW the 512 icon, which would then be
 * upsampled from a 320px bitmap. 384dpi is 320 × 384/72 ≈ 1707px, comfortably
 * above every size below, so all four downsample cleanly instead.
 */
const RASTER_DENSITY = 384;

/**
 * `inset` is the fraction of the canvas the artwork occupies.
 *
 * 1 for the `any` icons — the launcher draws them as-is. 0.6 for the maskable
 * one, because the spec's safe zone is a circle of 80% diameter and 0.6 clears
 * it with margin under both Android's circle and ChromeOS's squircle. 0.8 for
 * Apple, whose ~22% corner radius would otherwise clip the vine tips.
 *
 * White rather than transparent wherever a mask or an OS composites: iOS puts
 * transparency on BLACK, and the letterforms are black.
 *
 * Returns a buffer rather than writing to disk, so every derivation — this
 * included — runs, and can throw, before `main` writes a single byte.
 */
async function raster(svg: Buffer, size: number, inset: number, background: Rgba): Promise<Buffer> {
  const inner = Math.round(size * inset);
  const art = await sharp(svg, { density: RASTER_DENSITY })
    .resize(inner, inner, { fit: "contain", background: CLEAR })
    .png()
    .toBuffer();
  const offset = Math.round((size - inner) / 2);

  return sharp({ create: { width: size, height: size, channels: 4, background } })
    .composite([{ input: art, top: offset, left: offset }])
    .png({ compressionLevel: 9 })
    .toBuffer();
}

async function main() {
  const icon = tidy(readFileSync(join(ROOT, "assets/brand/ariko-icon.svg"), "utf8"));
  const logo = tidy(readFileSync(join(ROOT, "assets/brand/ariko-logo.svg"), "utf8"));

  const iconComponent = component("ArikoIcon", icon);
  const logoComponent = component("ArikoLogo", logo);
  const favicon = buildFavicon(icon);

  /**
   * The rasters are built from `iconSvg` — the tidied SVG with its literal
   * hex colours, not `iconComponent`'s JSX — because no rasteriser resolves
   * `currentColor` or `var(--ariko-leaf-*)`; sharp needs concrete colour
   * values on the page to paint anything at all.
   */
  const iconSvg = Buffer.from(icon);
  const icon192 = await raster(iconSvg, 192, 1, CLEAR);
  const icon512 = await raster(iconSvg, 512, 1, CLEAR);
  const iconMaskable512 = await raster(iconSvg, 512, 0.6, WHITE);
  const appleIcon = await raster(iconSvg, 180, 0.8, WHITE);

  // Every value above is fully derived — and every derivation step able to
  // throw already has — before anything touches disk. A palette change that
  // breaks the logo but not the icon fails here with a clean tree, rather
  // than leaving a half-updated set of seven committed artifacts.
  const files: Array<[string, string | Buffer]> = [
    ["components/brand/ariko-icon.tsx", iconComponent],
    ["components/brand/ariko-logo.tsx", logoComponent],
    ["app/icon.svg", favicon],
    ["public/icons/icon-192.png", icon192],
    ["public/icons/icon-512.png", icon512],
    ["public/icons/icon-maskable-512.png", iconMaskable512],
    ["app/apple-icon.png", appleIcon],
  ];

  mkdirSync(join(ROOT, "public/icons"), { recursive: true });
  for (const [path, data] of files) {
    writeFileSync(join(ROOT, path), data);
  }

  console.log(`brand: ${files.length} files written`);
}

/**
 * `main().catch(...)` rather than top-level await: this repo's package.json
 * carries no `"type": "module"`, so tsx transpiles a bare `.ts` script to
 * CommonJS, where top-level await is a syntax error. Mirrors the exit-on-error
 * shape of `scripts/migrate-retier.ts` and `scripts/check-orphan-assets.ts`.
 */
main().catch((err) => {
  console.error(err);
  process.exit(1);
});
