import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { optimize } from "svgo";
import sharp from "sharp";

/**
 * The only writer of derived brand artifacts. Two sources in
 * (`assets/brand/*.svg`), seven files out.
 *
 * It exists because the alternative is that the next person to change the logo
 * re-derives the colour mapping, the precision setting, the maskable safe zone
 * and the Apple background from scratch — or, far likelier, does not, and ships
 * a manifest icon that disagrees with the favicon.
 *
 * Run it by hand (`npm run brand:build`), not at build time: the brand changes
 * at the pace of a rebrand, not a deploy, and every output is committed.
 */

const ROOT = process.cwd();

/** The three literal colours the artwork ships, and the tokens they become. */
const INK = "#000";
const LEAF_DARK = "#006400";
const LEAF_LIGHT = "#90ee90";

/**
 * `removeViewBox: false` is not a preference. svgo's preset-default DELETES
 * viewBox when width/height are present, and `removeDimensions` then deletes
 * width/height — leaving a mark with no coordinate system at all. The two
 * plugins are only safe together in this order.
 */
function tidy(source: string): string {
  const { data } = optimize(source, {
    floatPrecision: 1,
    plugins: [
      { name: "preset-default", params: { overrides: { removeViewBox: false } } },
      "removeDimensions",
    ],
  });
  return data;
}

function viewBoxOf(svg: string): string {
  const found = svg.match(/viewBox="([^"]+)"/);
  if (!found) throw new Error("svgo stripped the viewBox — check the plugin overrides");
  return found[1];
}

/** svgo emits only these four on this artwork; anything else is a surprise worth failing on. */
const JSX_ATTR: Record<string, string> = {
  d: "d",
  fill: "fill",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
};

function toToken(value: string): string {
  const v = value.toLowerCase();
  if (v === INK) return "currentColor";
  if (v === LEAF_DARK) return "var(--ariko-leaf-dark)";
  if (v === LEAF_LIGHT) return "var(--ariko-leaf-light)";
  throw new Error(`unexpected colour ${value} — the artwork's palette changed`);
}

function pathsToJsx(svg: string): string {
  const tags = svg.match(/<path\b[^>]*\/?>/g) ?? [];
  if (tags.length === 0) throw new Error("no <path> elements — did the export change shape?");

  return tags
    .map((tag) => {
      const attrs = [...tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)].map(([, name, value]) => {
        const jsxName = JSX_ATTR[name];
        if (!jsxName) throw new Error(`unmapped SVG attribute \`${name}\``);
        return [jsxName, name === "fill" ? toToken(value) : value] as const;
      });
      const rendered = attrs.map(([n, v]) => `\n        ${n}="${v}"`).join("");
      return `      <path${rendered}\n      />`;
    })
    .join("\n");
}

function component(name: string, svg: string): string {
  return `import type { SVGProps } from "react";

// GENERATED by \`npm run brand:build\` from assets/brand/*.svg. Do not edit.

/**
 * The letterforms are painted with \`currentColor\`, so they follow the text
 * colour of whatever they sit in (\`text-foreground\`, \`text-primary\`, …). The
 * two leaf greens come from \`--ariko-leaf-dark\` / \`--ariko-leaf-light\`, which
 * \`app/globals.css\` re-declares under \`.dark\`.
 */
export function ${name}({ title, ...props }: SVGProps<SVGSVGElement> & { title?: string }) {
  return (
    <svg
      viewBox="${viewBoxOf(svg)}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
      role={title ? "img" : "presentation"}
      aria-hidden={title ? undefined : true}
    >
      {title ? <title>{title}</title> : null}
${pathsToJsx(svg)}
    </svg>
  );
}
`;
}

const CLEAR = { r: 0, g: 0, b: 0, alpha: 0 };
const WHITE = { r: 255, g: 255, b: 255, alpha: 1 };

/**
 * `inset` is the fraction of the canvas the artwork occupies.
 *
 * 1 for the `any` icons — the launcher draws them as-is. 0.6 for the maskable
 * one, because the spec's safe zone is a circle of 80% diameter and 0.6 clears
 * it with margin under both Android's circle and ChromeOS's squircle. 0.8 for
 * Apple, whose ~22% corner radius would otherwise clip the vine tips.
 *
 * White rather than transparent wherever a mask or an OS composites: iOS puts
 * transparency on BLACK, and the letterforms are black.
 */
async function raster(
  svg: Buffer,
  size: number,
  inset: number,
  background: typeof CLEAR,
  out: string,
) {
  const inner = Math.round(size * inset);
  const art = await sharp(svg, { density: 384 })
    .resize(inner, inner, { fit: "contain", background: CLEAR })
    .png()
    .toBuffer();
  const offset = Math.round((size - inner) / 2);

  await sharp({ create: { width: size, height: size, channels: 4, background } })
    .composite([{ input: art, top: offset, left: offset }])
    .png({ compressionLevel: 9 })
    .toFile(join(ROOT, out));
}

const icon = tidy(readFileSync(join(ROOT, "assets/brand/ariko-icon.svg"), "utf8"));
const logo = tidy(readFileSync(join(ROOT, "assets/brand/ariko-logo.svg"), "utf8"));

writeFileSync(join(ROOT, "components/brand/ariko-icon.tsx"), component("ArikoIcon", icon));
writeFileSync(join(ROOT, "components/brand/ariko-logo.tsx"), component("ArikoLogo", logo));

/**
 * The favicon is the one derivative that CANNOT use currentColor — it renders
 * outside the document. An embedded <style> gives it the same two-tone
 * behaviour the two `media`-switched PNGs had, in one file instead of 386 kB.
 */
const favicon = icon
  .replace(new RegExp(`fill="${INK}"`, "g"), 'class="ink"')
  .replace(
    /(<svg[^>]*>)/,
    "$1<style>.ink{fill:#111}@media(prefers-color-scheme:dark){.ink{fill:#fafafa}}</style>",
  );
writeFileSync(join(ROOT, "app/icon.svg"), favicon);

mkdirSync(join(ROOT, "public/icons"), { recursive: true });

/**
 * Wrapped in an IIFE rather than top-level await: this repo's package.json
 * carries no `"type": "module"`, so tsx transpiles a bare `.ts` script to
 * CommonJS, where top-level await is a syntax error.
 */
(async () => {
  const flat = Buffer.from(icon);
  await raster(flat, 192, 1, CLEAR, "public/icons/icon-192.png");
  await raster(flat, 512, 1, CLEAR, "public/icons/icon-512.png");
  await raster(flat, 512, 0.6, WHITE, "public/icons/icon-maskable-512.png");
  await raster(flat, 180, 0.8, WHITE, "app/apple-icon.png");

  console.log("brand: 7 files written");
})();
